create extension if not exists pgcrypto;

create table if not exists public.ecosystem_products (
  id uuid primary key default gen_random_uuid(),
  product_key text not null unique,
  name text not null,
  base_url text not null,
  config jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  username text,
  avatar_url text,
  full_name text,
  email text,
  tier text not null default 'free' check (tier in ('free', 'pro', 'enterprise')),
  subscription_status text,
  stripe_customer_id text,
  relay_external_id text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create unique index if not exists profiles_relay_external_id_key
  on public.profiles (relay_external_id)
  where relay_external_id is not null;

create index if not exists profiles_stripe_customer_id_idx
  on public.profiles (stripe_customer_id)
  where stripe_customer_id is not null;

create table if not exists public.user_product_roles (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references public.profiles(id) on delete cascade,
  product_id uuid not null references public.ecosystem_products(id) on delete cascade,
  role text not null check (role in ('owner', 'admin', 'editor', 'viewer')),
  permissions jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  unique(user_id, product_id)
);

create table if not exists public.analytics_metrics (
  id bigint generated by default as identity primary key,
  metric_name text not null,
  value numeric not null,
  dimensions jsonb not null default '{}'::jsonb,
  timestamp timestamptz not null default now()
);

create index if not exists idx_analytics_name_time
  on public.analytics_metrics (metric_name, timestamp desc);

create index if not exists idx_analytics_dimensions
  on public.analytics_metrics using gin (dimensions);

create table if not exists public.cumulus_ui_theme_profiles (
  product_key text primary key references public.ecosystem_products(product_key) on delete cascade,
  material text not null default 'standard' check (material in ('subtle', 'standard', 'strong', 'solid')),
  elevation text not null default 'e2' check (elevation in ('e1', 'e2', 'e3', 'e4')),
  theme_mode text not null default 'system' check (theme_mode in ('dark', 'light', 'system')),
  motion_mode text not null default 'full' check (motion_mode in ('full', 'reduced', 'off')),
  reduce_transparency boolean not null default false,
  glass_intensity numeric(3, 2) not null default 1.00 check (glass_intensity >= 0.70 and glass_intensity <= 1.30),
  noise_opacity numeric(3, 2) not null default 0.05 check (noise_opacity >= 0.00 and noise_opacity <= 0.40),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.cumulus_ui_user_preferences (
  user_id uuid not null references auth.users(id) on delete cascade,
  product_key text not null references public.ecosystem_products(product_key) on delete cascade,
  material text check (material in ('subtle', 'standard', 'strong', 'solid')),
  elevation text check (elevation in ('e1', 'e2', 'e3', 'e4')),
  theme_mode text check (theme_mode in ('dark', 'light', 'system')),
  motion_mode text check (motion_mode in ('full', 'reduced', 'off')),
  reduce_transparency boolean,
  glass_intensity numeric(3, 2) check (glass_intensity >= 0.70 and glass_intensity <= 1.30),
  noise_opacity numeric(3, 2) check (noise_opacity >= 0.00 and noise_opacity <= 0.40),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  primary key (user_id, product_key)
);

create table if not exists public.cumulus_auth_request_logs (
  id uuid primary key default gen_random_uuid(),
  created_at timestamptz not null default now(),
  request_id uuid not null,
  app_key text not null,
  event_type text not null,
  decision text not null,
  host text,
  path text,
  method text,
  redirect_to text,
  redirect_to_host text,
  redirect_allowed boolean,
  session_cookie_present boolean,
  user_valid boolean,
  stale_session boolean,
  attempt integer,
  status_code integer,
  ip_hash text,
  ua_hash text,
  metadata jsonb not null default '{}'::jsonb
);

create index if not exists idx_cumulus_auth_logs_created_at
  on public.cumulus_auth_request_logs (created_at desc);

create index if not exists idx_cumulus_auth_logs_request_id
  on public.cumulus_auth_request_logs (request_id);

create table if not exists public.shopify_stores (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references public.profiles(id) on delete cascade,
  shop_domain text not null unique,
  access_token text,
  shop_data jsonb not null default '{}'::jsonb,
  is_active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.shopify_products (
  id uuid primary key default gen_random_uuid(),
  store_id uuid not null references public.shopify_stores(id) on delete cascade,
  shopify_id text not null,
  title text,
  handle text,
  data jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique(store_id, shopify_id)
);

create or replace function public.set_cumulus_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

create or replace function public.handle_new_user()
returns trigger
language plpgsql
security definer
set search_path = public, auth, extensions
as $$
begin
  insert into public.profiles (id, full_name, avatar_url, email)
  values (
    new.id,
    coalesce(nullif(trim(new.raw_user_meta_data->>'full_name'), ''), new.email),
    new.raw_user_meta_data->>'avatar_url',
    new.email
  )
  on conflict (id) do update
    set full_name = coalesce(excluded.full_name, public.profiles.full_name),
        avatar_url = coalesce(excluded.avatar_url, public.profiles.avatar_url),
        email = coalesce(excluded.email, public.profiles.email),
        updated_at = now();

  return new;
end;
$$;

drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created
  after insert on auth.users
  for each row execute function public.handle_new_user();

drop trigger if exists trg_ecosystem_products_updated_at on public.ecosystem_products;
create trigger trg_ecosystem_products_updated_at
  before update on public.ecosystem_products
  for each row execute function public.set_cumulus_updated_at();

drop trigger if exists trg_profiles_updated_at on public.profiles;
create trigger trg_profiles_updated_at
  before update on public.profiles
  for each row execute function public.set_cumulus_updated_at();

drop trigger if exists trg_cumulus_ui_theme_profiles_updated_at on public.cumulus_ui_theme_profiles;
create trigger trg_cumulus_ui_theme_profiles_updated_at
  before update on public.cumulus_ui_theme_profiles
  for each row execute function public.set_cumulus_updated_at();

drop trigger if exists trg_cumulus_ui_user_preferences_updated_at on public.cumulus_ui_user_preferences;
create trigger trg_cumulus_ui_user_preferences_updated_at
  before update on public.cumulus_ui_user_preferences
  for each row execute function public.set_cumulus_updated_at();

alter table public.ecosystem_products enable row level security;
alter table public.profiles enable row level security;
alter table public.user_product_roles enable row level security;
alter table public.analytics_metrics enable row level security;
alter table public.cumulus_ui_theme_profiles enable row level security;
alter table public.cumulus_ui_user_preferences enable row level security;
alter table public.cumulus_auth_request_logs enable row level security;
alter table public.shopify_stores enable row level security;
alter table public.shopify_products enable row level security;

drop policy if exists "Public read products" on public.ecosystem_products;
create policy "Public read products"
  on public.ecosystem_products for select
  using (true);

drop policy if exists "Users read own profile" on public.profiles;
create policy "Users read own profile"
  on public.profiles for select
  using (auth.uid() = id);

drop policy if exists "Users update own profile" on public.profiles;
create policy "Users update own profile"
  on public.profiles for update
  using (auth.uid() = id)
  with check (auth.uid() = id);

drop policy if exists "Users read own roles" on public.user_product_roles;
create policy "Users read own roles"
  on public.user_product_roles for select
  using (auth.uid() = user_id);

drop policy if exists "Authenticated read analytics" on public.analytics_metrics;
create policy "Authenticated read analytics"
  on public.analytics_metrics for select
  to authenticated
  using (true);

drop policy if exists "Public read theme profiles" on public.cumulus_ui_theme_profiles;
create policy "Public read theme profiles"
  on public.cumulus_ui_theme_profiles for select
  using (true);

drop policy if exists "Users read own ui preferences" on public.cumulus_ui_user_preferences;
create policy "Users read own ui preferences"
  on public.cumulus_ui_user_preferences for select
  using (auth.uid() = user_id);

drop policy if exists "Users insert own ui preferences" on public.cumulus_ui_user_preferences;
create policy "Users insert own ui preferences"
  on public.cumulus_ui_user_preferences for insert
  with check (auth.uid() = user_id);

drop policy if exists "Users update own ui preferences" on public.cumulus_ui_user_preferences;
create policy "Users update own ui preferences"
  on public.cumulus_ui_user_preferences for update
  using (auth.uid() = user_id)
  with check (auth.uid() = user_id);

drop policy if exists "Users delete own ui preferences" on public.cumulus_ui_user_preferences;
create policy "Users delete own ui preferences"
  on public.cumulus_ui_user_preferences for delete
  using (auth.uid() = user_id);

drop policy if exists "Service role manage auth logs" on public.cumulus_auth_request_logs;
create policy "Service role manage auth logs"
  on public.cumulus_auth_request_logs for all
  to service_role
  using (true)
  with check (true);

drop policy if exists "Users manage own stores" on public.shopify_stores;
create policy "Users manage own stores"
  on public.shopify_stores for all
  using (auth.uid() = user_id)
  with check (auth.uid() = user_id);

drop policy if exists "Users manage own store products" on public.shopify_products;
create policy "Users manage own store products"
  on public.shopify_products for all
  using (
    exists (
      select 1
      from public.shopify_stores
      where shopify_stores.id = shopify_products.store_id
        and shopify_stores.user_id = auth.uid()
    )
  )
  with check (
    exists (
      select 1
      from public.shopify_stores
      where shopify_stores.id = shopify_products.store_id
        and shopify_stores.user_id = auth.uid()
    )
  );

insert into public.ecosystem_products (product_key, name, base_url, config)
values
  ('hub', 'Cumulus Hub', 'http://localhost:3000', '{"app":"hub"}'::jsonb),
  ('tado', 'Tado', 'https://github.com/cumulus/tado', '{"app":"agent-workspace"}'::jsonb),
  ('relay', 'Relay', 'https://relay.example.com', '{"app":"agent-onboarding"}'::jsonb)
on conflict (product_key) do update
set
  name = excluded.name,
  base_url = excluded.base_url,
  config = excluded.config,
  updated_at = now();

insert into public.cumulus_ui_theme_profiles (
  product_key,
  material,
  elevation,
  theme_mode,
  motion_mode,
  reduce_transparency,
  glass_intensity,
  noise_opacity
)
values
  ('hub', 'standard', 'e2', 'system', 'full', false, 1.00, 0.05),
  ('tado', 'standard', 'e2', 'system', 'full', false, 1.00, 0.05),
  ('relay', 'standard', 'e2', 'system', 'full', false, 1.00, 0.05)
on conflict (product_key) do update
set
  material = excluded.material,
  elevation = excluded.elevation,
  theme_mode = excluded.theme_mode,
  motion_mode = excluded.motion_mode,
  reduce_transparency = excluded.reduce_transparency,
  glass_intensity = excluded.glass_intensity,
  noise_opacity = excluded.noise_opacity,
  updated_at = now();

create or replace function public.purge_cumulus_auth_request_logs(retention_days int default 30)
returns integer
language plpgsql
security definer
set search_path = public
as $$
declare
  deleted_count integer;
begin
  delete from public.cumulus_auth_request_logs
  where created_at < now() - make_interval(days => retention_days);

  get diagnostics deleted_count = row_count;
  return deleted_count;
end;
$$;

revoke all on function public.purge_cumulus_auth_request_logs(int) from public;
grant execute on function public.purge_cumulus_auth_request_logs(int) to service_role;
